#!/usr/bin/env node
// One-off generator for data/world-map.js (committed output; rerun only to
// change projection or country set).
//
// Dev-only dependencies — install anywhere and point NODE_PATH at it:
//   npm i topojson-client world-atlas d3-geo
//   node scripts/build-map.js [path-to-node_modules]
//
// Output: data/world-map.js -> window.LAUNCH_MAP = { w, h, countries: { ISO3: { n: name, d: svgPath } } }
// Uses Natural Earth 110m (public domain) via the world-atlas package,
// equirectangular projection clipped to malaria-relevant latitudes.

const path = require("path");
const fs = require("fs");

const extra = process.argv[2];
if (extra) module.paths.unshift(path.resolve(extra));

const topojson = require("topojson-client");
const { geoEquirectangular, geoPath } = require("d3-geo");
const world = require(require.resolve("world-atlas/countries-110m.json"));

// ISO 3166-1 numeric -> alpha-3 for the countries we may ever need to color:
// malaria-endemic Africa, Middle East pockets, South/Southeast Asia, Latin America.
const NUM_TO_A3 = {
  "024":"AGO","204":"BEN","072":"BWA","854":"BFA","108":"BDI","120":"CMR","132":"CPV","140":"CAF","148":"TCD","174":"COM","178":"COG","180":"COD","384":"CIV","262":"DJI","818":"EGY","226":"GNQ","232":"ERI","748":"SWZ","231":"ETH","266":"GAB","270":"GMB","288":"GHA","324":"GIN","624":"GNB","404":"KEN","426":"LSO","430":"LBR","434":"LBY","450":"MDG","454":"MWI","466":"MLI","478":"MRT","480":"MUS","504":"MAR","508":"MOZ","516":"NAM","562":"NER","566":"NGA","646":"RWA","678":"STP","686":"SEN","690":"SYC","694":"SLE","706":"SOM","710":"ZAF","728":"SSD","729":"SDN","834":"TZA","768":"TGO","788":"TUN","800":"UGA","894":"ZMB","716":"ZWE",
  "004":"AFG","050":"BGD","064":"BTN","104":"MMR","116":"KHM","144":"LKA","156":"CHN","356":"IND","360":"IDN","364":"IRN","368":"IRQ","408":"PRK","410":"KOR","418":"LAO","458":"MYS","524":"NPL","586":"PAK","598":"PNG","608":"PHL","626":"TLS","702":"SGP","704":"VNM","760":"SYR","764":"THA","887":"YEM","682":"SAU","512":"OMN",
  "068":"BOL","076":"BRA","170":"COL","188":"CRI","192":"CUB","214":"DOM","218":"ECU","222":"SLV","254":"GUF","320":"GTM","328":"GUY","332":"HTI","340":"HND","484":"MEX","558":"NIC","591":"PAN","600":"PRY","604":"PER","740":"SUR","862":"VEN","032":"ARG"
};

const W = 960, H = 420;
const projection = geoEquirectangular().fitExtent(
  [[0, 0], [W, H]],
  { type: "MultiPoint", coordinates: [[-120, 42], [155, -40]] } // window covering endemic belt
);
const pathGen = geoPath(projection);

const feats = topojson.feature(world, world.objects.countries).features;
const out = {};
for (const f of feats) {
  const a3 = NUM_TO_A3[String(f.id).padStart(3, "0")];
  if (!a3) continue;
  const d = pathGen(f);
  if (!d) continue;
  out[a3] = { n: f.properties.name, d: d.replace(/(\d+\.\d{1})\d+/g, "$1") };
}

const file =
  "// GENERATED by scripts/build-map.js from world-atlas (Natural Earth, public domain).\n" +
  "// Do not edit by hand; rerun the generator instead.\n" +
  "window.LAUNCH_MAP = " +
  JSON.stringify({ w: W, h: H, countries: out }) + ";\n";

fs.writeFileSync(path.join(__dirname, "..", "data", "world-map.js"), file);
console.log("Wrote data/world-map.js — " + Object.keys(out).length + " countries, " + Math.round(file.length / 1024) + " KB");
