#!/usr/bin/env node
// Generates a dated "what changed" brief (Markdown) from the dashboard data:
//   node scripts/make-brief.js [--since YYYY-MM-DD]
//
// Sources: data/products.js (current state), the changelog (what changed and
// when), and — when one exists from before the window — the closest history/
// snapshot, used to diff stage statuses. Output: briefs/launch-brief-<date>.md
// (also refreshed as briefs/latest.md for a stable link).
//
// Default window: 90 days before meta.lastUpdated — a quarterly brief.

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const STATUS_LABEL = { done: "Complete", prog: "In progress", late: "Delayed", idle: "Not started" };

function parse(text) {
  const m = text.match(/^window\.LAUNCH_DATA\s*=\s*/m);
  return JSON.parse(text.slice(m.index + m[0].length).replace(/;?\s*$/, ""));
}
const load = f => parse(fs.readFileSync(f, "utf8"));

const data = load(path.join(root, "data", "products.js"));
const today = data.meta.lastUpdated;

const argIdx = process.argv.indexOf("--since");
let since;
if (argIdx > -1) {
  since = process.argv[argIdx + 1];
} else {
  const d = new Date(today + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() - 90);
  since = d.toISOString().slice(0, 10);
}

// closest snapshot dated ON or BEFORE the window start = the comparison baseline
const histDir = path.join(root, "history");
let baseline = null, baselineDate = null;
if (fs.existsSync(histDir)) {
  const candidates = fs.readdirSync(histDir)
    .map(f => (f.match(/^products-(\d{4}-\d{2}-\d{2})\.js$/) || [])[1])
    .filter(d => d && d <= since)
    .sort();
  if (candidates.length) {
    baselineDate = candidates[candidates.length - 1];
    baseline = load(path.join(histDir, `products-${baselineDate}.js`));
  }
}

const tracked = data.products.filter(p => !p.placeholder);
const flagged = tracked.filter(p => p.flag);
const changes = (data.changelog || []).filter(c => c.date >= since && c.date <= today);

// stage-status diffs vs baseline
const moves = [];
if (baseline) {
  for (const p of tracked) {
    const old = baseline.products.find(q => q.id === p.id);
    if (!old || old.placeholder) { moves.push(`**${p.name}** — newly tracked since ${baselineDate}.`); continue; }
    p.stages.forEach((s, i) => {
      const o = (old.stages || [])[i];
      if (o && o.status !== s.status)
        moves.push(`**${p.name}** · ${data.stages[i]}: ${STATUS_LABEL[o.status]} → **${STATUS_LABEL[s.status]}**` +
          (s.status === "late" ? ` — ${s.note}` : ""));
    });
  }
}

// data gaps
const tbc = [];
for (const p of tracked) {
  const c = p.detail.country;
  ["registered", "inGuidelines", "inMft"].forEach(k => { if (c[k] === "TBC") tbc.push(`${p.name}: country ${k}`); });
  if ((p.detail.price.value || "").trim() === "TBC") tbc.push(`${p.name}: price`);
  if (!p.detail.volume) tbc.push(`${p.name}: procurement volumes`);
}

const md = `# LAUNCH brief — what changed

**Window:** ${since} → ${today} · **Data status:** ${data.meta.dataStatus}${data.meta.dataStatus !== "live" ? " (verify before external use)" : ""}
${baseline ? `**Baseline for status comparisons:** history snapshot of ${baselineDate}` : "**Baseline:** none before this window — this brief is the baseline; future briefs will diff against snapshots in \`history/\`."}

## Where products stand

| Product | Current stage | Bottleneck |
| --- | --- | --- |
${tracked.map(p => `| ${p.name} (${p.inn}) | ${data.stages[p.currentStage]} | ${p.flag ? "🔴 " + p.flag : "—"} |`).join("\n")}

## Stage movements${baseline ? ` since ${baselineDate}` : ""}

${moves.length ? moves.map(m => `- ${m}`).join("\n") : baseline ? "- No stage-status changes in this window." : "- (No pre-window snapshot to diff against.)"}

## Logged updates in this window (${changes.length})

${changes.length ? changes.map(c => `- **${c.date} · ${c.product}** — ${c.change}`).join("\n") : "- None recorded."}

## Active bottlenecks (${flagged.length})

${flagged.length ? flagged.map(p => `- **${p.name}** — ${p.flag}`).join("\n") : "- None."}

## Open data gaps (${tbc.length} TBC values)

${tbc.map(t => `- ${t}`).join("\n") || "- None — all values sourced."}

---
*Generated by \`scripts/make-brief.js\` from \`data/products.js\`. Publicly available
information only; unverified values are TBC, never estimated. Dashboard:
https://kochrisdev.github.io/launch-transparency-dashboard/*
`;

const outDir = path.join(root, "briefs");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, `launch-brief-${today}.md`), md);
fs.writeFileSync(path.join(outDir, "latest.md"), md);
console.log(`Wrote briefs/launch-brief-${today}.md (window ${since} → ${today}, ` +
  `${moves.length} stage movement(s), ${changes.length} logged update(s), ${tbc.length} TBC gap(s))`);
